// Lista de cidades do mundo todo para autocomplete
export const worldCities = [
  // América do Norte
  "Nova York, Estados Unidos",
  "Los Angeles, Estados Unidos",
  "Chicago, Estados Unidos",
  "Miami, Estados Unidos",
  "Las Vegas, Estados Unidos",
  "San Francisco, Estados Unidos",
  "Orlando, Estados Unidos",
  "Boston, Estados Unidos",
  "Seattle, Estados Unidos",
  "Washington D.C., Estados Unidos",
  "Toronto, Canadá",
  "Vancouver, Canadá",
  "Montreal, Canadá",
  "Cidade do México, México",
  "Cancún, México",
  "Playa del Carmen, México",
  "Tulum, México",
  "Guadalajara, México",
  
  // América do Sul
  "São Paulo, Brasil",
  "Rio de Janeiro, Brasil",
  "Brasília, Brasil",
  "Salvador, Brasil",
  "Fortaleza, Brasil",
  "Belo Horizonte, Brasil",
  "Manaus, Brasil",
  "Curitiba, Brasil",
  "Recife, Brasil",
  "Porto Alegre, Brasil",
  "Florianópolis, Brasil",
  "Foz do Iguaçu, Brasil",
  "Gramado, Brasil",
  "Bonito, Brasil",
  "Fernando de Noronha, Brasil",
  "Jericoacoara, Brasil",
  "Maragogi, Brasil",
  "Porto de Galinhas, Brasil",
  "Búzios, Brasil",
  "Paraty, Brasil",
  "Campos do Jordão, Brasil",
  "Buenos Aires, Argentina",
  "Bariloche, Argentina",
  "Mendoza, Argentina",
  "Ushuaia, Argentina",
  "Lima, Peru",
  "Cusco, Peru",
  "Machu Picchu, Peru",
  "Santiago, Chile",
  "Valparaíso, Chile",
  "Bogotá, Colômbia",
  "Cartagena, Colômbia",
  "Medellín, Colômbia",
  "Quito, Equador",
  "Galápagos, Equador",
  "Montevidéu, Uruguai",
  "Punta del Este, Uruguai",
  "La Paz, Bolívia",
  "Uyuni, Bolívia",
  
  // Europa
  "Londres, Reino Unido",
  "Paris, França",
  "Roma, Itália",
  "Barcelona, España",
  "Madrid, España",
  "Amsterdã, Holanda",
  "Berlim, Alemanha",
  "Munique, Alemanha",
  "Viena, Áustria",
  "Praga, República Tcheca",
  "Budapeste, Hungria",
  "Varsóvia, Polônia",
  "Lisboa, Portugal",
  "Porto, Portugal",
  "Atenas, Grécia",
  "Santorini, Grécia",
  "Mykonos, Grécia",
  "Veneza, Itália",
  "Florença, Itália",
  "Milão, Itália",
  "Nápoles, Itália",
  "Dublin, Irlanda",
  "Edimburgo, Escócia",
  "Copenhague, Dinamarca",
  "Estocolmo, Suécia",
  "Oslo, Noruega",
  "Helsinque, Finlândia",
  "Reykjavik, Islândia",
  "Zurique, Suíça",
  "Genebra, Suíça",
  "Bruxelas, Bélgica",
  "Bruges, Bélgica",
  "Luxemburgo, Luxemburgo",
  "Mônaco, Mônaco",
  "Moscou, Rússia",
  "São Petersburgo, Rússia",
  "Istambul, Turquia",
  
  // Ásia
  "Tóquio, Japão",
  "Kyoto, Japão",
  "Osaka, Japão",
  "Hiroshima, Japão",
  "Pequim, China",
  "Xangai, China",
  "Hong Kong, China",
  "Macau, China",
  "Seul, Coreia do Sul",
  "Busan, Coreia do Sul",
  "Bangkok, Tailândia",
  "Phuket, Tailândia",
  "Chiang Mai, Tailândia",
  "Singapura, Singapura",
  "Kuala Lumpur, Malásia",
  "Bali, Indonésia",
  "Jacarta, Indonésia",
  "Hanói, Vietnã",
  "Ho Chi Minh, Vietnã",
  "Manila, Filipinas",
  "Boracay, Filipinas",
  "Mumbai, Índia",
  "Nova Delhi, Índia",
  "Jaipur, Índia",
  "Agra, Índia",
  "Goa, Índia",
  "Dubai, Emirados Árabes",
  "Abu Dhabi, Emirados Árabes",
  "Doha, Catar",
  "Tel Aviv, Israel",
  "Jerusalém, Israel",
  "Beirute, Líbano",
  
  // África
  "Cairo, Egito",
  "Luxor, Egito",
  "Marrakech, Marrocos",
  "Casablanca, Marrocos",
  "Cidade do Cabo, África do Sul",
  "Joanesburgo, África do Sul",
  "Nairóbi, Quênia",
  "Zanzibar, Tanzânia",
  "Seychelles, Seychelles",
  "Maurício, Maurício",
  "Tunis, Tunísia",
  
  // Oceania
  "Sydney, Austrália",
  "Melbourne, Austrália",
  "Brisbane, Austrália",
  "Perth, Austrália",
  "Gold Coast, Austrália",
  "Auckland, Nova Zelândia",
  "Queenstown, Nova Zelândia",
  "Wellington, Nova Zelândia",
  "Fiji, Fiji",
  "Bora Bora, Polinésia Francesa",
  "Tahiti, Polinésia Francesa",
  
  // Caribe
  "Havana, Cuba",
  "Punta Cana, República Dominicana",
  "Santo Domingo, República Dominicana",
  "San Juan, Porto Rico",
  "Kingston, Jamaica",
  "Montego Bay, Jamaica",
  "Nassau, Bahamas",
  "Barbados, Barbados",
  "Aruba, Aruba",
  "Curaçao, Curaçao",
  "Santa Lúcia, Santa Lúcia",
  
  // América Central
  "San José, Costa Rica",
  "Cidade do Panamá, Panamá",
  "Cidade da Guatemala, Guatemala",
  "San Salvador, El Salvador",
  "Tegucigalpa, Honduras",
  "Manágua, Nicarágua",
  "Belize City, Belize",
];

export function searchCities(query: string): string[] {
  if (!query || query.length < 2) {
    return [];
  }

  const normalizedQuery = query
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

  return worldCities
    .filter((city) => {
      const normalizedCity = city
        .toLowerCase()
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "");
      return normalizedCity.includes(normalizedQuery);
    })
    .slice(0, 10); // Limita a 10 sugestões
}
